---
title: "IPF Cell Atlas: Read-in"
output:
  github_document:
    toc: true
  html_notebook:
    toc: true
---

This version uses the Imran integration that has developmental cells built-in.

# Environment
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(Seurat)
library(SeuratWrappers)
library(monocle3)
library(RColorBrewer)
spectral.colors <- colorRampPalette(rev(brewer.pal(9,'Spectral')))
```
# Read in GSE136831
```{r}
original.dir <- ('~/vcalab-files/datasets/GSE136831_IPF_Cell_Atlas/')
metadata <- read_tsv(paste0(original.dir,'GSE136831_AllCells.Samples.CellType.MetadataTable.txt.gz'))
metadata <- as.data.frame(metadata)
rownames(metadata) <- metadata$CellBarcode_Identity

features <- read_tsv(paste0(original.dir,'GSE136831_AllCells.GeneIDs.txt.gz'))
cells <- read_tsv(paste0(original.dir,'GSE136831_AllCells.cellBarcodes.txt.gz'), col_names = F)

counts <- Matrix::readMM(paste0(original.dir,'GSE136831_RawCounts_Sparse.mtx.gz'))
rownames(counts) <- features$HGNC_EnsemblAlt_GeneID
colnames(counts) <- cells$X1
```
```{r}
ipfatlas.cells <- CreateSeuratObject(counts=counts, meta.data=metadata)
```
```{r}
rm(counts,cells,features,metadata)
gc()
```

# Standard preprocessing
## Filter overall dataset
```{r}
ipfatlas.cells[['percent.mt']] <- PercentageFeatureSet(ipfatlas.cells, pattern='^MT-')
VlnPlot(ipfatlas.cells, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0)
```
```{r}
ipfatlas.cells <- subset(ipfatlas.cells, subset = nFeature_RNA > 200 & nFeature_RNA < 5000 & percent.mt < 10)
```

## Proceed with epithelium
```{r}
ipfatlas.epi.cells <- subset(ipfatlas.cells, subset=CellType_Category=='Epithelial')
```

```{r}
ipfatlas.epi.cells <- NormalizeData(ipfatlas.epi.cells)
ipfatlas.epi.cells <- FindVariableFeatures(ipfatlas.epi.cells)
ipfatlas.epi.cells <- ScaleData(ipfatlas.epi.cells, features=rownames(ipfatlas.epi.cells))
ipfatlas.epi.cells <- RunPCA(ipfatlas.epi.cells)
ipfatlas.epi.cells <- RunUMAP(ipfatlas.epi.cells, dims=1:30)
```
```{r}
DimPlot(ipfatlas.epi.cells, group.by='Manuscript_Identity')
DimPlot(ipfatlas.epi.cells, group.by='Subclass_Cell_Identity')
DimPlot(ipfatlas.epi.cells, group.by='Subject_Identity')
DimPlot(ipfatlas.epi.cells, group.by='Disease_Identity')
```
```{r}
FeaturePlot(ipfatlas.epi.cells, features=c('CLDN4','KRT8','LGALS3','GDF15'))
```


# Dot plots using mouse equivalent fibrotic DATP genes
Accepts the published annotations as accurate.

```{r}
ipfatlas.epi.ipf.cells <- subset(ipfatlas.epi.cells, subset=Disease_Identity=='IPF')
ipfatlas.epi.ctrl.cells <- subset(ipfatlas.epi.cells, subset=Disease_Identity=='Control')
```


```{r}
DotPlot(ipfatlas.epi.ipf.cells, features=c('CLDN4','KRT8','LGALS3','GDF15'),
        group.by='Manuscript_Identity')
DotPlot(ipfatlas.epi.ctrl.cells, features=c('CLDN4','KRT8','LGALS3','GDF15'),
        group.by='Manuscript_Identity')
```
```{r}
DotPlot(ipfatlas.epi.ipf.cells, features=c('CLDN4','KRT8','LGALS3','GDF15'),
        group.by='Subclass_Cell_Identity')
DotPlot(ipfatlas.epi.ctrl.cells, features=c('CLDN4','KRT8','LGALS3','GDF15'),
        group.by='Subclass_Cell_Identity')
```
```{r}
DotPlot(ipfatlas.epi.ipf.cells, features=c('KRT7','KRT8','LGALS3','TP63','KRT17','CLDN4','GDF15'),
        group.by='Manuscript_Identity',
        cols='Spectral')
```
Collapse the non-basal airway cells
```{r}
Idents(ipfatlas.epi.ipf.cells) <- 'Manuscript_Identity'
ipfatlas.epi.ipf.cells <- RenameIdents(ipfatlas.epi.ipf.cells,
                                       `Ionocyte`='Other Airway',
                                       `Goblet`='Other Airway',
                                       `Club`='Other Airway',
                                       `Ciliated`='Other Airway',
                                       `PNEC`='Other Airway')
```
```{r}
DotPlot(ipfatlas.epi.ipf.cells, features=c('KRT7','KRT8','LGALS3','TP63','KRT17','CLDN4','GDF15'),
        cols='Spectral')
```



